package main

import (
	"log"
)

func handleError(err error) {
	log.Print(err)
}
